[versions]
awaitility = "4.2.2"
caffeine = "3.2.0"
junit = "5.11.4"
rxjava = "3.1.10"
versions = "0.52.0"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
