[versions]
caffeine = "3.2.0"
junit = "5.11.4"
reactor = "3.7.2"
truth = "1.4.4"
versions = "0.51.0"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
