name: Retrieve and submit dependency graph
permissions: {}
on:
  workflow_run:
    workflows: ['Generate and save dependency graph']
    types: [completed]

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 24

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptium.net:443
            api.github.com:443
            caffeine.gradle-enterprise.cloud:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            github.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            services.gradle.org:443
      - name: Retrieve and submit dependency graph
        uses: gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        with:
          dependency-graph: download-and-submit
