name: examples
permissions: read-all
on: [ push, pull_request ]

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 21

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.adoptium.net:443
            caffeine.gradle-enterprise.cloud:443
            download.oracle.com:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            gds.oracle.com:443
            github.com:443
            jcenter.bintray.com:443
            objects.githubusercontent.com:443
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            services.gradle.org:443
            www.graalvm.org:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          add-job-summary: never
          cache-read-only: false
      - name: Simulator
        run: >
          ./gradlew simulator:run
          -Dcaffeine.simulator.report.output=$(pwd)/simulation.md
          -Dcaffeine.simulator.files.paths.0="corda:trace_vaultservice.gz"
          -Dcaffeine.simulator.files.paths.1="lirs:loop.trace.gz"
          -Dcaffeine.simulator.files.paths.2="corda:trace_vaultservice.gz"
      - name: Publish Simulator Results
        run: |
          {
            echo '### Adaptivity'
            echo '```'
            cat $(pwd)/simulation.md
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
      - name: Chart Simulation
        run: ./gradlew -q simulator:simulate --maximumSize=100,200,300
      - name: Memory Overhead
        run: ./gradlew -q caffeine:memoryOverhead
      - name: Stresser (read)
        run: >
          timeout 1m ./gradlew -q caffeine:stress --workload=read
          || ([[ $? -eq 124 ]] && echo "Timeout reached, but that's OK")
      - name: Stresser (write)
        run: >
          timeout 1m ./gradlew -q caffeine:stress --workload=write
          || ([[ $? -eq 124 ]] && echo "Timeout reached, but that's OK")
      - name: Stresser (refresh)
        run: >
          timeout 1m ./gradlew -q caffeine:stress --workload=refresh
          || ([[ $? -eq 124 ]] && echo "Timeout reached, but that's OK")
      - name: Write-behind (rxjava)
        working-directory: examples/write-behind-rxjava
        run: ./gradlew build
      - name: Coalescing Bulkloader (reactor)
        working-directory: examples/coalescing-bulkloader-reactor
        run: ./gradlew build
      - name: Hibernate (jcache)
        working-directory: examples/hibernate
        run: ./gradlew build
      - name: Indexable
        working-directory: examples/indexable
        run: ./gradlew build
      - name: Resilience (failsafe)
        working-directory: examples/resilience-failsafe
        run: ./gradlew build
      - name: Prepare for Graal Native Image
        uses: ./.github/actions/run-gradle
        env:
          SNAPSHOT: true
        with:
          java: GraalVM
          token: ${{ secrets.GITHUB_TOKEN }}
          arguments: -q caffeine:clean caffeine:jar
      - name: Graal Native Image
        uses: ./.github/actions/run-gradle
        env:
          SNAPSHOT: true
        with:
          java: GraalVM
          token: ${{ secrets.GITHUB_TOKEN }}
          arguments: >
            --project-dir examples/graal-native
            -Pagent run
            metadataCopy --task run --dir src/main/resources/META-INF/native-image
            nativeRun nativeTest
