name: Qodana
permissions: {}
on: [ push ]

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 11

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptium.net:443
            api.foojay.io:443
            api.github.com:443
            auth.docker.io:443
            caffeine.gradle-enterprise.cloud:443
            docs.oracle.com:443
            download.jetbrains.com:443
            download-cdn.jetbrains.com:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            errorprone.info:443
            github.com:443
            guava.dev:443
            jcenter.bintray.com:443
            jspecify.dev:443
            lightbend.github.io:443
            objects.githubusercontent.com:443
            packages.jetbrains.team:443
            pkg-cdn.jetbrains.team:443
            plugins.gradle.org:443
            plugins.jetbrains.com:443
            plugins-artifacts.gradle.org:443
            prod.fus.aws.intellij.net:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            repo.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            resources.jetbrains.com:443
            services.gradle.org:443
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Build
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: check -x test
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@27de2a744479d1d731934eeaf79287575ebc5dd3 # v2025.2.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
