name: Trivy Vulnerability Scanner
permissions: {}
on: [ push, pull_request ]

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
            github.com:443
            mirror.gcr.io:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # v0.33.0
        continue-on-error: true
        with:
          scan-type: fs
          format: sarif
          output: results.sarif
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: results.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        if: steps.check_files.outputs.files_exists == 'true'
        with:
            sarif_file: results.sarif
